# Generated by Django 4.2.1 on 2024-03-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('u_password', models.CharField(max_length=20)),
                ('u_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('press_count', models.IntegerField()),
            ],
            options={
                'db_table': 'user_data',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20)),
                ('press_count', models.IntegerField(default=0)),
            ],
        ),
    ]
