# Generated by Django 4.2.1 on 2024-01-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20)),
                ('press_count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='count',
        ),
    ]
